/* Drawescape V5 — real WebGL + Canvas game prototype
   Works without a build step. Three.js is loaded dynamically; if CDN fails, Canvas fallback keeps the app usable. */
(() => {
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const clamp = (v,a,b)=>Math.max(a,Math.min(b,v));
  const lerp = (a,b,t)=>a+(b-a)*t;
  const TAU = Math.PI*2;
  const storageKey = 'drawescape-v5-state';
  const state = {
    progress:{}, perspectiveMode:'one', natureMode:'wind', emotion:'quiet',
    three:null, objects:[], selected:null, sceneData:[], views:[], palette:[]
  };

  function toast(msg){ const t=$('#toast'); t.textContent=msg; t.hidden=false; clearTimeout(t._id); t._id=setTimeout(()=>t.hidden=true,2200); }
  function saveState(){ localStorage.setItem(storageKey, JSON.stringify({progress:state.progress,views:state.views,palette:state.palette})); $('#saveStatus').textContent='saved locally'; }
  function loadState(){ try{ const d=JSON.parse(localStorage.getItem(storageKey)||'{}'); state.progress=d.progress||{}; state.views=d.views||[]; state.palette=d.palette||[]; }catch(e){} }
  function downloadDataUrl(name, dataUrl){ const a=document.createElement('a'); a.download=name; a.href=dataUrl; a.click(); }
  function downloadText(name, text){ const blob=new Blob([text],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
  function resizeCanvasToDisplay(canvas){ const r=canvas.getBoundingClientRect(); const dpr=Math.min(devicePixelRatio||1,2); const w=Math.max(1,Math.round(r.width*dpr)); const h=Math.max(1,Math.round(r.height*dpr)); if(canvas.width!==w||canvas.height!==h){ canvas.width=w; canvas.height=h; return true;} return false; }
  function getPos(canvas, ev){ const r=canvas.getBoundingClientRect(); const t=ev.touches?ev.touches[0]:ev; return {x:(t.clientX-r.left)*canvas.width/r.width, y:(t.clientY-r.top)*canvas.height/r.height}; }
  function hslToHex(h,s,l){ h=((h%360)+360)%360; s/=100; l/=100; const c=(1-Math.abs(2*l-1))*s; const x=c*(1-Math.abs((h/60)%2-1)); const m=l-c/2; let r=0,g=0,b=0; if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x} return '#'+[r,g,b].map(v=>Math.round((v+m)*255).toString(16).padStart(2,'0')).join(''); }
  function hexToRgb(hex){ hex=hex.replace('#',''); if(hex.length===3) hex=hex.split('').map(x=>x+x).join(''); const n=parseInt(hex,16); return {r:(n>>16)&255,g:(n>>8)&255,b:n&255}; }
  function rgbToHex(r,g,b){ return '#'+[r,g,b].map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join(''); }
  function mix(c1,c2,t){ const a=hexToRgb(c1),b=hexToRgb(c2); return rgbToHex(lerp(a.r,b.r,t),lerp(a.g,b.g,t),lerp(a.b,b.b,t)); }
  function shade(hex,amt){ return mix(hex, amt>0?'#ffffff':'#07111f', Math.abs(amt)); }

  // Navigation and theme
  function initUI(){
    $$('[data-jump]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.jump)?.scrollIntoView({behavior:'smooth'})));
    $('#themeBtn').addEventListener('click',()=>document.body.classList.toggle('sleep'));
    $('#focusBtn').addEventListener('click',()=>document.body.classList.toggle('focus'));
    $('#resetProgress').addEventListener('click',()=>{ state.progress={}; saveState(); renderMap(); toast('进度已重置'); });
    renderMap(); renderKnowledge();
  }

  const mapNodes = [
    ['线之海','点线面 / 拓扑 / 轮廓随视角变化','拓扑线笔','#4ab9cf','webglLab'],
    ['比例森林','锚点 / 单位长度 / 人体关系记忆','比例罗盘','#8ebf94','faceLab'],
    ['相机塔','视平线 / 消失点 / 焦距 / 观察方式','透视眼镜','#6e93e8','perspectiveLab'],
    ['深度湖','近中远 / 遮挡 / 深度图 / 空气透视','深度灯笼','#8c75df','natureLab'],
    ['光之月台','法线 / 明暗交界线 / 投影 / AO','法线罗盘','#ffd166','shadingLab'],
    ['褶皱剧场','固定点 / 拉力 / 重力 / 材料硬度','布料风铃','#f39ab2','shadingLab'],
    ['材质星市','粗糙度 / 菲涅尔 / SSS / 高光形状','材质晶球','#ffad6e','paletteLab'],
    ['风水流体谷','风 / 水 / 烟 / 云 / 看不见的力','流体叶片','#4ab9cf','natureLab'],
    ['折叠云城','漫画 / 动漫 / Q版 / 自己的风格','风格棱镜','#8c75df','emotionLab']
  ];
  function renderMap(){ const box=$('#worldMap'); box.innerHTML=''; mapNodes.forEach((n,i)=>{ const done=!!state.progress[n[0]]; const el=document.createElement('article'); el.className='mapNode'; el.style.setProperty('--nodeColor',n[3]); el.innerHTML=`<span class="badge">${done?'已点亮':'待探索'}</span><h3>${i+1}. ${n[0]}</h3><b>${n[2]}</b><p>${n[1]}</p><button data-jump="${n[4]}">进入星区</button>`; el.querySelector('button').addEventListener('click',()=>{ state.progress[n[0]]=true; saveState(); $('#'+n[4]).scrollIntoView({behavior:'smooth'}); renderMap(); }); box.appendChild(el); }); }
  function renderKnowledge(){ const cards=[
    ['透视 / 成像','针孔相机、视平线、消失点、FOV。绘画里的透视网格，本质是相机投影的可视化。',['欧洲线性透视训练','Computer Graphics camera projection','摄影焦距与视角']],
    ['计算机视觉 / 对齐','从多视角照片匹配关键点，建立一致坐标系。绘画里的锚点测量，就是手工 keypoint alignment。',['Keypoint matching','Epipolar geometry','SfM / MVS / SLAM']],
    ['建模 / 拓扑','线稿里的轮廓、中心线、截面线分别对应建模里的边界、路径、剖面和曲面。',['Blender mesh / NURBS','Rhino Sweep / Loft / Revolve','SketchUp push-pull']],
    ['光影 / 渲染','明暗交界线来自法线与光线关系，AO 来自缝隙对环境光的遮挡，高光来自视线与反射方向。',['Lambert diffuse','Specular / roughness','Ambient occlusion']],
    ['褶皱 / 力学','褶皱从固定点出发，沿拉力与重力组织；材料越硬，折线越清楚；越软，过渡越连续。',['Cloth simulation','Tension / compression','Material stiffness']],
    ['风格 / 认知','风格不是装饰，是信息压缩策略：保留什么、夸张什么、删除什么、让观者如何感受。',['Visual abstraction','Comics language','Color psychology / composition']]
  ]; const grid=$('#knowledgeGrid'); grid.innerHTML=''; cards.forEach(c=>{ const el=document.createElement('article'); el.className='kcard'; el.innerHTML=`<h3>${c[0]}</h3><p>${c[1]}</p><ul>${c[2].map(x=>`<li>${x}</li>`).join('')}</ul>`; grid.appendChild(el); }); }

  // Cover animation
  function initCover(){ const c=$('#coverCanvas'), ctx=c.getContext('2d'); let t=0; function draw(){ const w=c.width,h=c.height; ctx.clearRect(0,0,w,h); const grd=ctx.createLinearGradient(0,0,w,h); grd.addColorStop(0,'#06133f'); grd.addColorStop(.5,'#4f5de7'); grd.addColorStop(1,'#ffd166'); ctx.fillStyle=grd; ctx.fillRect(0,0,w,h); ctx.globalAlpha=.55; for(let i=0;i<90;i++){ const x=(Math.sin(i*17.1+t*.012)+1)*w*.5; const y=(Math.cos(i*9.3+t*.009)+1)*h*.5; ctx.fillStyle=i%3?'#fff8':'#ffd166aa'; ctx.beginPath(); ctx.arc(x,y,(i%5)+1,0,TAU); ctx.fill(); } ctx.globalAlpha=1; const cx=w*.52, cy=h*.52; ctx.strokeStyle='#ffffff44'; ctx.lineWidth=1; for(let k=0;k<14;k++){ ctx.beginPath(); ctx.ellipse(cx,cy,80+k*24,34+k*10,Math.sin(t*.006)*.2,0,TAU); ctx.stroke(); } const pts=[]; for(let i=0;i<7;i++){ const a=i/7*TAU+t*.01; const r=90+Math.sin(t*.02+i)*24; pts.push([cx+Math.cos(a)*r,cy+Math.sin(a)*r*.72]); } ctx.strokeStyle='#fff'; ctx.lineWidth=5; ctx.lineJoin='round'; ctx.beginPath(); pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p)); ctx.closePath(); ctx.stroke(); ctx.strokeStyle='#57d4df'; ctx.lineWidth=2; pts.forEach(p=>{ ctx.beginPath(); ctx.moveTo(p[0],p[1]); ctx.lineTo(cx,cy); ctx.stroke(); }); ctx.fillStyle='#fff'; ctx.font='900 28px Nunito, sans-serif'; ctx.fillText('SCAN → FOLD → DRAW',42,70); ctx.font='900 18px Nunito, sans-serif'; ctx.fillStyle='#fffbd3'; ctx.fillText('Perspective / light / cloth / feeling / style',42,98); t++; requestAnimationFrame(draw); } draw(); }

  // WebGL 3D Lab
  let THREE, renderer, scene, camera, raycaster, pointer, light, ambient, grid, axes;
  const cam = {yaw:0.72,pitch:0.38,radius:9,target:{x:0,y:.8,z:0},height:1.4};
  const mouse = {down:false,shift:false,moved:false,x:0,y:0,lastX:0,lastY:0};
  async function loadThree(){
    if(window.THREE){ THREE=window.THREE; return true; }
    const urls=['https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js','https://unpkg.com/three@0.160.0/build/three.min.js'];
    for(const u of urls){ try{ await new Promise((res,rej)=>{ const s=document.createElement('script'); s.src=u; s.onload=res; s.onerror=rej; document.head.appendChild(s); setTimeout(()=>rej(new Error('timeout')),7000); }); if(window.THREE){THREE=window.THREE;return true;} }catch(e){} }
    return false;
  }
  function initWebGLLab(){ const mount=$('#threeMount'); const fallback=$('#fallback3D'); const overlay=$('#projectionOverlay'); resizeCanvasToDisplay(fallback); resizeCanvasToDisplay(overlay);
    loadThree().then(ok=>{ if(ok) startThree(); else { $('#webglStatus').textContent='Three.js 未加载，使用 Canvas 2.5D 备用引擎'; startFallback3D(); } });
    $$('[data-add]').forEach(b=>b.addEventListener('click',()=>addShape(b.dataset.add)));
    const controls=['fovRange','camHeight','lightAz','lightEl','roughness','metalness','wireToggle','showHorizon','showProjection','animeRange','chibiRange','lineWeight3D'];
    controls.forEach(id=>$('#'+id)?.addEventListener('input',()=>{ updateControlLabels(); updateMaterials(); updateCamera(); drawProjectionOverlay(); }));
    $('#saveViewBtn').addEventListener('click',saveView); $('#savedViewsSelect').addEventListener('change',loadView); $('#shot3DBtn').addEventListener('click',shot3D); $('#exportSceneBtn').addEventListener('click',exportScene);
    window.addEventListener('resize',()=>{ if(renderer) resizeRenderer(); resizeCanvasToDisplay(overlay); resizeCanvasToDisplay(fallback); });
    updateSavedViews(); updateControlLabels();
  }
  function startThree(){ $('#webglStatus').textContent='WebGL 已启动：真实 3D / 相机 / 光照 / 投影'; const mount=$('#threeMount'); $('#fallback3D').style.display='none';
    scene=new THREE.Scene(); scene.background=new THREE.Color(0xf3fbff); camera=new THREE.PerspectiveCamera(50,1,.1,1000); renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,alpha:false}); renderer.setPixelRatio(Math.min(devicePixelRatio||1,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; mount.insertBefore(renderer.domElement,$('#projectionOverlay')); raycaster=new THREE.Raycaster(); pointer=new THREE.Vector2();
    ambient=new THREE.HemisphereLight(0xffffff,0x8192a0,.9); scene.add(ambient); light=new THREE.DirectionalLight(0xffffff,2.2); light.castShadow=true; light.shadow.mapSize.set(1024,1024); scene.add(light);
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0xf8f1df,roughness:.82,metalness:0})); floor.rotation.x=-Math.PI/2; floor.position.y=-1; floor.receiveShadow=true; floor.userData.static=true; scene.add(floor);
    grid=new THREE.GridHelper(30,30,0x7fb5c9,0xd8e1e9); grid.position.y=-.995; scene.add(grid); axes=new THREE.AxesHelper(3); scene.add(axes);
    addShape('room'); addShape('head'); addShape('cloth'); addShape('tree'); addShape('ribbon');
    updateCamera(); updateLight(); resizeRenderer(); bindThreeEvents(); animateThree(); }
  function resizeRenderer(){ const r=$('#threeMount').getBoundingClientRect(); renderer.setSize(r.width,r.height,false); camera.aspect=r.width/r.height; camera.updateProjectionMatrix(); resizeCanvasToDisplay($('#projectionOverlay')); drawProjectionOverlay(); }
  function updateCamera(){ if(!camera) return; const fov=+$('#fovRange').value; cam.height=+$('#camHeight').value; camera.fov=fov; camera.updateProjectionMatrix(); const cp=Math.cos(cam.pitch); camera.position.set(cam.target.x+Math.sin(cam.yaw)*cp*cam.radius, cam.target.y+Math.sin(cam.pitch)*cam.radius+cam.height, cam.target.z+Math.cos(cam.yaw)*cp*cam.radius); camera.lookAt(cam.target.x,cam.target.y+cam.height*.22,cam.target.z); $('#fovVal').textContent=fov+'°'; $('#camHeightVal').textContent=cam.height.toFixed(1); }
  function updateLight(){ if(!light) return; const az=+$('#lightAz').value*Math.PI/180, el=+$('#lightEl').value*Math.PI/180; const r=8; light.position.set(Math.cos(az)*Math.cos(el)*r,Math.sin(el)*r,Math.sin(az)*Math.cos(el)*r); }
  function updateMaterials(){ updateLight(); const rough=+$('#roughness').value, metal=+$('#metalness').value; $('#roughVal').textContent=rough.toFixed(2); $('#metalVal').textContent=metal.toFixed(2); state.objects.forEach(o=>{ o.traverse?.(m=>{ if(m.material && m.material.roughness!==undefined){ m.material.roughness=rough; m.material.metalness=metal; m.material.wireframe=$('#wireToggle').checked; m.material.needsUpdate=true; }}); }); $('#animeVal').textContent=(+$('#animeRange').value).toFixed(2); $('#chibiVal').textContent=(+$('#chibiRange').value).toFixed(2); $('#lineWeight3DVal').textContent=$('#lineWeight3D').value; if(state.objects.some(o=>o.userData.kind==='head')) rebuildHeadStyles(); }
  function updateControlLabels(){ $('#lightAzVal').textContent=$('#lightAz').value+'°'; $('#lightElVal').textContent=$('#lightEl').value+'°'; $('#fovVal').textContent=$('#fovRange').value+'°'; $('#camHeightVal').textContent=(+$('#camHeight').value).toFixed(1); }
  function mat(color){ return new THREE.MeshStandardMaterial({color,roughness:+$('#roughness').value,metalness:+$('#metalness').value}); }
  function addShape(kind){ if(!THREE){ fallbackAdd(kind); return; } let obj; const colorMap={box:0x78b7e6,sphere:0xf39ab2,cylinder:0xffd166,cone:0x8ebf94,torus:0x8c75df,ribbon:0x57d4df,room:0xe8d5b6,head:0xffc6a1,tree:0x80b878,cloth:0xe99fc5};
    if(kind==='box') obj=new THREE.Mesh(new THREE.BoxGeometry(1.6,1.6,1.6),mat(colorMap.box));
    else if(kind==='sphere') obj=new THREE.Mesh(new THREE.SphereGeometry(.9,48,28),mat(colorMap.sphere));
    else if(kind==='cylinder') obj=new THREE.Mesh(new THREE.CylinderGeometry(.65,.65,1.8,40),mat(colorMap.cylinder));
    else if(kind==='cone') obj=new THREE.Mesh(new THREE.ConeGeometry(.75,1.9,40),mat(colorMap.cone));
    else if(kind==='torus') obj=new THREE.Mesh(new THREE.TorusGeometry(.75,.18,18,70),mat(colorMap.torus));
    else if(kind==='room') obj=makeRoom();
    else if(kind==='head') obj=makeHead();
    else if(kind==='tree') obj=makeTree();
    else if(kind==='cloth') obj=makeCloth();
    else if(kind==='ribbon') obj=makeRibbon();
    if(!obj) return; obj.userData.kind=kind; obj.userData.note=shapeNote(kind); obj.position.x=(Math.random()-.5)*3; obj.position.z=(Math.random()-.5)*3; if(kind==='room') obj.position.set(0,0,0); obj.traverse?.(m=>{ if(m.isMesh){m.castShadow=true;m.receiveShadow=true;m.userData.root=obj;} }); scene.add(obj); state.objects.push(obj); selectObject(obj); drawProjectionOverlay(); toast('已添加：'+kind); }
  function makeRoom(){ const g=new THREE.Group(); const m=mat(0xeedfc9); const back=new THREE.Mesh(new THREE.BoxGeometry(6,.08,4),m); back.position.set(0,1,-3); const left=new THREE.Mesh(new THREE.BoxGeometry(.08,3.8,5),m); left.position.set(-3,.9,-.5); const right=left.clone(); right.position.x=3; const ceil=new THREE.Mesh(new THREE.BoxGeometry(6,.08,5),m); ceil.position.set(0,2.8,-.5); const floor=new THREE.Mesh(new THREE.BoxGeometry(6,.08,5),mat(0xf7ebd4)); floor.position.set(0,-1,-.5); [back,left,right,ceil,floor].forEach(x=>g.add(x)); return g; }
  function makeHead(){ const g=new THREE.Group(); const head=new THREE.Mesh(new THREE.SphereGeometry(.78,48,32),mat(0xffc9a6)); head.scale.set(.82,1.08,.72); g.add(head); const nose=new THREE.Mesh(new THREE.ConeGeometry(.12,.38,24),mat(0xf3a77e)); nose.rotation.x=Math.PI/2; nose.position.set(0,.02,.62); g.add(nose); const eyeMat=new THREE.MeshStandardMaterial({color:0x23313f,roughness:.3}); [-.25,.25].forEach(x=>{ const e=new THREE.Mesh(new THREE.SphereGeometry(.055,16,10),eyeMat); e.position.set(x,.22,.56); e.scale.set(1.6,.72,.36); g.add(e); }); const mouth=new THREE.Mesh(new THREE.TorusGeometry(.16,.012,8,32,Math.PI),new THREE.MeshStandardMaterial({color:0x9c4354})); mouth.position.set(0,-.33,.58); mouth.rotation.x=Math.PI/2; g.add(mouth); g.userData.kind='head'; return g; }
  function rebuildHeadStyles(){ if(!THREE) return; const anime=+$('#animeRange').value, chibi=+$('#chibiRange').value; state.objects.filter(o=>o.userData.kind==='head').forEach(g=>{ const head=g.children[0]; if(head){ head.scale.set(lerp(.82,1.05,chibi),lerp(1.08,1.32,chibi),lerp(.72,.68,anime)); } g.children.forEach((c,i)=>{ if(i>=2&&i<=3){ const sx=lerp(1.6,2.8,anime); c.scale.set(sx,lerp(.72,1.15,anime),.36); c.position.y=lerp(.22,.28,chibi); } }); }); }
  function makeTree(){ const g=new THREE.Group(); const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.16,.22,1.6,16),mat(0x8a5a3d)); trunk.position.y=-.2; const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.9,2),mat(0x78b978)); crown.position.y=.9; crown.scale.set(1.15,.8,1); g.add(trunk,crown); return g; }
  function makeCloth(){ const geo=new THREE.PlaneGeometry(2.2,1.35,26,12); const pos=geo.attributes.position; for(let i=0;i<pos.count;i++){ const x=pos.getX(i), y=pos.getY(i); pos.setZ(i, Math.sin(x*6)*.08*Math.cos(y*4)); } pos.needsUpdate=true; geo.computeVertexNormals(); const m=mat(0xe99fc5); m.side=THREE.DoubleSide; const mesh=new THREE.Mesh(geo,m); mesh.rotation.x=-.25; mesh.position.y=.25; return mesh; }
  function makeRibbon(){ const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-1,0,0),new THREE.Vector3(-.3,.35,.4),new THREE.Vector3(.35,-.1,-.2),new THREE.Vector3(1,.45,.2)]); const tube=new THREE.TubeGeometry(curve,80,.05,10,false); const mesh=new THREE.Mesh(tube,mat(0x57d4df)); return mesh; }
  function shapeNote(kind){ const notes={box:'盒体训练一点/两点透视，所有边都应该服从同一个坐标系。',sphere:'球体最适合理解明暗交界线：没有硬边，只有法线连续变化。',cylinder:'圆柱连接椭圆透视、截面、轴线和体积。',cone:'圆锥帮助理解中心线、底面椭圆和轮廓随视角变化。',torus:'环形结构帮助理解穿插、内外轮廓和遮挡。',ribbon:'飘带是路径扫掠：画它先找中心线，再画宽度和扭转。',room:'房间是透视学院：地面、墙面、天花板必须共享消失点。',head:'人头不是符号，是球/盒体/楔形鼻子的组合和锚点系统。',tree:'自然物也有几何：树干轴线、树冠团块、枝叶节奏。',cloth:'褶皱从固定点和拉力出发，不是随机线条。'}; return notes[kind]||'形体是信息压缩的单位。'; }
  function selectObject(obj){ state.selected=obj; state.objects.forEach(o=>o.traverse?.(m=>{ if(m.material&&m.material.emissive) m.material.emissive.setHex(0x000000); })); obj?.traverse?.(m=>{ if(m.material&&m.material.emissive) m.material.emissive.setHex(0x151515); }); $('#selectedInfo').innerHTML=`<b>${obj?.userData.kind||'无选中'}</b><p>${obj?.userData.note||'点击物体后，这里会解释它的绘画意义。'}</p>`; }
  function bindThreeEvents(){ const dom=renderer.domElement; dom.addEventListener('pointerdown',ev=>{ mouse.down=true; mouse.shift=ev.shiftKey; mouse.moved=false; mouse.x=mouse.lastX=ev.clientX; mouse.y=mouse.lastY=ev.clientY; dom.setPointerCapture(ev.pointerId); }); dom.addEventListener('pointermove',ev=>{ if(!mouse.down) return; const dx=ev.clientX-mouse.lastX, dy=ev.clientY-mouse.lastY; mouse.lastX=ev.clientX; mouse.lastY=ev.clientY; if(Math.abs(ev.clientX-mouse.x)+Math.abs(ev.clientY-mouse.y)>4) mouse.moved=true; if(mouse.shift && state.selected){ state.selected.position.x += dx*.012; state.selected.position.y -= dy*.012; } else { cam.yaw -= dx*.006; cam.pitch = clamp(cam.pitch - dy*.005, -.9, .95); updateCamera(); } drawProjectionOverlay(); }); dom.addEventListener('pointerup',ev=>{ mouse.down=false; if(!mouse.moved) pickObject(ev); }); dom.addEventListener('wheel',ev=>{ ev.preventDefault(); cam.radius=clamp(cam.radius+ev.deltaY*.01,3,28); updateCamera(); drawProjectionOverlay(); },{passive:false}); }
  function pickObject(ev){ const rect=renderer.domElement.getBoundingClientRect(); pointer.x=((ev.clientX-rect.left)/rect.width)*2-1; pointer.y=-((ev.clientY-rect.top)/rect.height)*2+1; raycaster.setFromCamera(pointer,camera); const meshes=[]; state.objects.forEach(o=>o.traverse?.(m=>{ if(m.isMesh) meshes.push(m); })); const hit=raycaster.intersectObjects(meshes,true)[0]; if(hit){ selectObject(hit.object.userData.root||hit.object); } }
  function animateThree(){ requestAnimationFrame(animateThree); const t=performance.now()*0.001; state.objects.forEach(o=>{ if(o.userData.kind==='ribbon') o.rotation.z=Math.sin(t)*.12; if(o.userData.kind==='tree') o.rotation.z=Math.sin(t*1.2)*.035; if(o.userData.kind==='cloth'){ const pos=o.geometry?.attributes?.position; if(pos){ for(let i=0;i<pos.count;i++){ const x=pos.getX(i), y=pos.getY(i); pos.setZ(i, Math.sin(x*7+t*1.4)*.08*Math.cos(y*4)); } pos.needsUpdate=true; o.geometry.computeVertexNormals(); } } }); updateLight(); renderer.render(scene,camera); drawProjectionOverlay(); }
  function project(v){ const p=v.clone().project(camera); const c=$('#projectionOverlay'); return {x:(p.x*.5+.5)*c.width, y:(-p.y*.5+.5)*c.height, visible:p.z<1}; }
  function drawProjectionOverlay(){ const c=$('#projectionOverlay'), ctx=c.getContext('2d'); resizeCanvasToDisplay(c); ctx.clearRect(0,0,c.width,c.height); if(!camera) return; const showH=$('#showHorizon').checked, showP=$('#showProjection').checked; if(showH){ const y=c.height*(.5 - Math.sin(cam.pitch)*.42); ctx.strokeStyle='rgba(74,185,207,.55)'; ctx.lineWidth=2; ctx.setLineDash([12,10]); ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(c.width,y); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle='rgba(26,45,60,.75)'; ctx.font=`${14*(devicePixelRatio||1)}px Nunito`; ctx.fillText('视平线 / eye level',20,y-8); }
    if(showP && THREE){ ctx.lineWidth=+$('#lineWeight3D').value; ctx.strokeStyle='rgba(36,49,63,.72)'; ctx.fillStyle='rgba(255,209,102,.9)'; state.objects.forEach(o=>{ const center=new THREE.Vector3(); o.getWorldPosition(center); const p=project(center); if(!p.visible) return; ctx.beginPath(); ctx.arc(p.x,p.y,4*(devicePixelRatio||1),0,TAU); ctx.fill(); const axes=[new THREE.Vector3(1,0,0),new THREE.Vector3(0,1,0),new THREE.Vector3(0,0,1)]; axes.forEach((a,idx)=>{ const q=project(center.clone().add(a.multiplyScalar(1.2))); ctx.beginPath(); ctx.moveTo(p.x,p.y); ctx.lineTo(q.x,q.y); ctx.strokeStyle=['rgba(228,106,106,.6)','rgba(142,191,148,.65)','rgba(74,185,207,.65)'][idx]; ctx.stroke(); }); }); }
  }
  function saveView(){ if(!renderer) return; const view={time:new Date().toLocaleString(),yaw:cam.yaw,pitch:cam.pitch,radius:cam.radius,height:cam.height,fov:+$('#fovRange').value,shot:renderer.domElement.toDataURL('image/png')}; state.views.push(view); if(state.views.length>20) state.views.shift(); saveState(); updateSavedViews(); toast('已保存视角与截图'); }
  function updateSavedViews(){ const s=$('#savedViewsSelect'); s.innerHTML='<option value="">读取保存视角</option>'+state.views.map((v,i)=>`<option value="${i}">${i+1}. ${v.time}</option>`).join(''); }
  function loadView(){ const idx=+$('#savedViewsSelect').value; const v=state.views[idx]; if(!v) return; cam.yaw=v.yaw; cam.pitch=v.pitch; cam.radius=v.radius; cam.height=v.height; $('#fovRange').value=v.fov; $('#camHeight').value=v.height; updateCamera(); updateControlLabels(); toast('视角已恢复'); }
  function shot3D(){ if(renderer) downloadDataUrl('drawescape_3d_view.png',renderer.domElement.toDataURL('image/png')); else downloadDataUrl('drawescape_canvas3d.png',$('#fallback3D').toDataURL('image/png')); }
  function exportScene(){ const data=state.objects.map(o=>({kind:o.userData.kind,position:o.position,rotation:o.rotation,scale:o.scale,note:o.userData.note})); downloadText('drawescape_scene.json',JSON.stringify({camera:cam,objects:data},null,2)); }
  // fallback 3D simple visual
  function startFallback3D(){ function draw(){ const c=$('#fallback3D'),ctx=c.getContext('2d'); resizeCanvasToDisplay(c); ctx.clearRect(0,0,c.width,c.height); ctx.fillStyle='#eef7fb'; ctx.fillRect(0,0,c.width,c.height); ctx.strokeStyle='#94b6c8'; for(let i=0;i<16;i++){ const y=c.height*.75-i*30; ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(c.width,y-i*16); ctx.stroke(); } ctx.fillStyle='#78b7e6'; ctx.fillRect(c.width*.42,c.height*.35,120,120); ctx.strokeStyle='#24313f'; ctx.strokeRect(c.width*.42,c.height*.35,120,120); requestAnimationFrame(draw); } draw(); }
  function fallbackAdd(){ toast('Canvas 备用模式：真实 3D 需要网络加载 Three.js'); }

  // Perspective canvas
  const persp = {mode:'one', horizon:.48, vp1:{x:.5,y:.48}, vp2:{x:.08,y:.48}, vp3:{x:.62,y:-.32}, dragging:null, drawing:false, strokes:[], current:null};
  function initPerspective(){ const c=$('#perspectiveCanvas'), ctx=c.getContext('2d'); function redraw(){ resizeCanvasToDisplay(c); const w=c.width,h=c.height; ctx.clearRect(0,0,w,h); ctx.fillStyle='#fffdf6'; ctx.fillRect(0,0,w,h); drawPaperTexture(ctx,w,h); const alpha=+$('#guideAlpha').value; const density=+$('#gridDensity').value; const hy=persp.horizon*h; ctx.strokeStyle=`rgba(74,185,207,${alpha})`; ctx.lineWidth=2; ctx.beginPath(); ctx.moveTo(0,hy); ctx.lineTo(w,hy); ctx.stroke(); ctx.fillStyle='rgba(35,49,60,.75)'; ctx.font=`${15*(devicePixelRatio||1)}px Nunito`; ctx.fillText('视平线 horizon',20,hy-10);
      const pts=[]; if(persp.mode==='one') pts.push(persp.vp1); if(persp.mode==='two'||persp.mode==='three') pts.push(persp.vp2,persp.vp1); if(persp.mode==='three') pts.push(persp.vp3); if(persp.mode==='ortho') drawAxonometric(ctx,w,h,density,alpha); else drawPerspectiveGrid(ctx,w,h,pts,density,alpha);
      pts.forEach((p,i)=>{ ctx.fillStyle=['#ffd166','#6e93e8','#f39ab2'][i]; ctx.beginPath(); ctx.arc(p.x*w,p.y*h,11*(devicePixelRatio||1),0,TAU); ctx.fill(); ctx.fillStyle='#22313c'; ctx.fillText('VP'+(i+1),p.x*w+14,p.y*h-10); });
      ctx.lineCap='round'; ctx.lineJoin='round'; [...persp.strokes, persp.current].filter(Boolean).forEach(s=>{ ctx.strokeStyle=s.color; ctx.lineWidth=s.size*(devicePixelRatio||1); ctx.beginPath(); s.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)); ctx.stroke(); }); updatePerspectiveExplain(); }
    function down(ev){ const p=getPos(c,ev); const w=c.width,h=c.height; const handles=[['vp1',persp.vp1],['vp2',persp.vp2],['vp3',persp.vp3],['horizon',{x:.04,y:persp.horizon}]]; for(const [name,hp] of handles){ if(Math.hypot(p.x-hp.x*w,p.y-hp.y*h)<28*(devicePixelRatio||1)){ persp.dragging=name; return; } } persp.drawing=true; persp.current={color:$('#drawColor').value,size:+$('#brushSize').value,points:[p]}; }
    function move(ev){ const p=getPos(c,ev); if(persp.dragging){ if(persp.dragging==='horizon'){ persp.horizon=clamp(p.y/c.height,.08,.9); persp.vp1.y=persp.vp2.y=persp.horizon; } else { persp[persp.dragging].x=clamp(p.x/c.width,-.5,1.5); persp[persp.dragging].y=clamp(p.y/c.height,-.7,1.5); if(persp.dragging!=='vp3') persp.horizon=persp[persp.dragging].y; } redraw(); return; } if(persp.drawing){ persp.current.points.push(p); redraw(); } }
    function up(){ if(persp.dragging) persp.dragging=null; if(persp.drawing&&persp.current){ persp.strokes.push(persp.current); persp.current=null; persp.drawing=false; } }
    c.addEventListener('pointerdown',down); c.addEventListener('pointermove',move); window.addEventListener('pointerup',up); $('#perspectiveModes').addEventListener('click',e=>{ if(e.target.dataset.mode){ persp.mode=e.target.dataset.mode; $$('#perspectiveModes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===persp.mode)); redraw(); }}); ['gridDensity','guideAlpha','drawColor','brushSize'].forEach(id=>$('#'+id).addEventListener('input',redraw)); $('#clearPerspectiveDraw').addEventListener('click',()=>{persp.strokes=[]; redraw();}); $('#shotPerspectiveBtn').addEventListener('click',()=>downloadDataUrl('drawescape_perspective.png',c.toDataURL('image/png'))); window.addEventListener('resize',redraw); redraw(); }
  function drawPaperTexture(ctx,w,h){ ctx.save(); ctx.globalAlpha=.12; ctx.strokeStyle='#cdbf9a'; for(let x=0;x<w;x+=22){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();} for(let y=0;y<h;y+=22){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();} ctx.restore(); }
  function drawPerspectiveGrid(ctx,w,h,pts,density,alpha){ pts.forEach(p=>{ const px=p.x*w,py=p.y*h; ctx.strokeStyle=`rgba(110,147,232,${alpha*.55})`; for(let i=0;i<=density;i++){ const x=i/density*w; ctx.beginPath(); ctx.moveTo(px,py); ctx.lineTo(x,h); ctx.stroke(); } }); ctx.strokeStyle=`rgba(255,173,110,${alpha*.55})`; for(let y=h*.58;y<h;y+=Math.max(14,h/(density*1.7))){ ctx.beginPath(); ctx.moveTo(0,y); ctx.bezierCurveTo(w*.3,y-35,w*.7,y-35,w,y); ctx.stroke(); } }
  function drawAxonometric(ctx,w,h,density,alpha){ const cx=w*.5, cy=h*.54; ctx.strokeStyle=`rgba(110,147,232,${alpha})`; for(let i=-density;i<=density;i++){ ctx.beginPath(); ctx.moveTo(cx+i*40-w,cy+i*14+h); ctx.lineTo(cx+i*40+w,cy+i*14-h); ctx.stroke(); ctx.beginPath(); ctx.moveTo(cx+i*40-w,cy-i*14-h); ctx.lineTo(cx+i*40+w,cy-i*14+h); ctx.stroke(); } }
  function updatePerspectiveExplain(){ const map={one:'一点透视：正面对着你，深度方向汇聚到一个消失点。适合走廊、铁轨、正面房间。',two:'两点透视：物体角对着你，左右两组平行线各自汇聚。适合街角、盒子、建筑外观。',three:'三点透视：再加入上下方向汇聚。适合仰视高楼、俯视深井、强烈漫画镜头。',ortho:'正交/轴测：减少近大远小，强调结构完整性。适合设计图、古画、图解和建模思维。'}; $('#perspectiveExplain').innerHTML=`<b>${persp.mode} perspective</b><p>${map[persp.mode]}</p>`; }

  // Shading and folds
  function initShading(){ const ids=['shadeAngle','shadeHeight','formComplexity','foldTension','clothStiffness']; ids.forEach(id=>$('#'+id).addEventListener('input',drawShading)); $('#shotShadingBtn').addEventListener('click',()=>downloadDataUrl('drawescape_shading_folds.png',mergeCanvases([$('#shadingCanvas'),$('#foldCanvas')]))); drawShading(); }
  function drawShading(){ const c=$('#shadingCanvas'),ctx=c.getContext('2d'); resizeCanvasToDisplay(c); const w=c.width,h=c.height; ctx.clearRect(0,0,w,h); ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,w,h); const angle=+$('#shadeAngle').value*Math.PI/180, height=+$('#shadeHeight').value/80, complexity=+$('#formComplexity').value; $('#shadeAngleVal').textContent=$('#shadeAngle').value+'°'; $('#shadeHeightVal').textContent=$('#shadeHeight').value+'°'; const cx=w*.48,cy=h*.48,r=Math.min(w,h)*.26; const lx=Math.cos(angle)*Math.cos(height), ly=Math.sin(angle)*Math.cos(height), lz=Math.sin(height);
    const img=ctx.createImageData(w,h); for(let y=0;y<h;y++){ for(let x=0;x<w;x++){ const dx=(x-cx)/r, dy=(y-cy)/r; const rr=dx*dx+dy*dy; const idx=(y*w+x)*4; if(rr<=1){ let z=Math.sqrt(1-rr); const bump=Math.sin(dx*12)*Math.sin(dy*8)*complexity*.18; const nx=dx+bump, ny=dy+bump*.5, nz=z; const len=Math.hypot(nx,ny,nz); const dot=clamp((nx*lx+ny*ly+nz*lz)/len,-1,1); const diff=clamp(dot*.78+.26,0,1); const ao=clamp(1-rr*.22,0,1); const val=diff*ao; img.data[idx]=lerp(50,255,val); img.data[idx+1]=lerp(62,226,val); img.data[idx+2]=lerp(74,196,val); img.data[idx+3]=255; } else { img.data[idx+3]=0; } } } ctx.putImageData(img,0,0); ctx.strokeStyle='rgba(35,49,60,.75)'; ctx.lineWidth=3*(devicePixelRatio||1); ctx.beginPath(); for(let a=0;a<TAU;a+=.02){ const x=cx+Math.cos(a)*r, y=cy+Math.sin(a)*r; const dx=(x-cx)/r,dy=(y-cy)/r,z=Math.sqrt(Math.max(0,1-dx*dx-dy*dy)); const dot=dx*lx+dy*ly+z*lz; if(Math.abs(dot)<.025){ if(ctx._started) ctx.lineTo(x,y); else{ctx.moveTo(x,y);ctx._started=true;} }} ctx.stroke(); ctx._started=false; ctx.fillStyle='#22313c'; ctx.font=`${16*(devicePixelRatio||1)}px Nunito`; ctx.fillText('黑线 = 明暗交界线（法线与光线接近垂直）',20,32*(devicePixelRatio||1)); ctx.strokeStyle='#ffd166'; ctx.lineWidth=5*(devicePixelRatio||1); ctx.beginPath(); ctx.moveTo(w*.82,h*.22); ctx.lineTo(w*.82+Math.cos(angle)*70,h*.22+Math.sin(angle)*70); ctx.stroke(); drawFold(); }
  function drawFold(){ const c=$('#foldCanvas'),ctx=c.getContext('2d'); resizeCanvasToDisplay(c); const w=c.width,h=c.height; ctx.clearRect(0,0,w,h); ctx.fillStyle='#fffaf0';ctx.fillRect(0,0,w,h); const tension=+$('#foldTension').value, stiff=+$('#clothStiffness').value; const pins=[[w*.25,h*.2],[w*.75,h*.2]]; ctx.fillStyle='#e46a6a'; pins.forEach(p=>{ctx.beginPath();ctx.arc(p[0],p[1],8*(devicePixelRatio||1),0,TAU);ctx.fill();}); const waves=7+Math.round(stiff*10); for(let i=0;i<waves;i++){ const t=i/(waves-1); const sx=lerp(pins[0][0],pins[1][0],t); const top=lerp(pins[0][1],pins[1][1],t); const len=lerp(h*.55,h*.28,Math.abs(t-.5)*2)+tension*h*.18*Math.sin(t*TAU); ctx.strokeStyle=`rgba(36,49,63,${lerp(.25,.85,1-Math.abs(t-.5))})`; ctx.lineWidth=lerp(1,4,stiff)*(devicePixelRatio||1); ctx.beginPath(); ctx.moveTo(sx,top); for(let k=0;k<40;k++){ const u=k/39; const x=sx + Math.sin(u*Math.PI*2*(1+stiff*2)+t*4)*lerp(8,28,1-stiff)*u; const y=top + u*len + Math.sin(u*Math.PI*4+t*TAU)*12*(1-stiff); k?ctx.lineTo(x,y):ctx.moveTo(x,y); } ctx.stroke(); } ctx.fillStyle='rgba(255,209,102,.22)'; ctx.beginPath(); ctx.moveTo(pins[0][0],pins[0][1]); ctx.quadraticCurveTo(w*.5,h*.62,pins[1][0],pins[1][1]); ctx.lineTo(w*.78,h*.74); ctx.quadraticCurveTo(w*.5,h*.92,w*.22,h*.74); ctx.closePath(); ctx.fill(); ctx.fillStyle='#22313c'; ctx.font=`${16*(devicePixelRatio||1)}px Nunito`; ctx.fillText('褶皱 = 固定点 + 重力 + 张力 + 材质硬度',20,32*(devicePixelRatio||1)); }
  function mergeCanvases(canvases){ const w=canvases.reduce((a,c)=>a+c.width,0), h=Math.max(...canvases.map(c=>c.height)); const out=document.createElement('canvas'); out.width=w; out.height=h; const ctx=out.getContext('2d'); let x=0; canvases.forEach(c=>{ctx.drawImage(c,x,0);x+=c.width;}); return out.toDataURL('image/png'); }

  // Face lab
  function initFace(){ ['faceYaw','facePitch','faceAnime','faceChibi','faceShade','faceGuides'].forEach(id=>$('#'+id).addEventListener('input',drawFace)); $('#shotFaceBtn').addEventListener('click',()=>downloadDataUrl('drawescape_face_style.png',$('#faceCanvas').toDataURL('image/png'))); drawFace(); }
  function drawFace(){ const c=$('#faceCanvas'),ctx=c.getContext('2d'); resizeCanvasToDisplay(c); const w=c.width,h=c.height; ctx.clearRect(0,0,w,h); ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,w,h); const yaw=+$('#faceYaw').value/55, pitch=+$('#facePitch').value/35, anime=+$('#faceAnime').value, chibi=+$('#faceChibi').value, shade=+$('#faceShade').value; $('#faceYawVal').textContent=$('#faceYaw').value+'°'; $('#facePitchVal').textContent=$('#facePitch').value+'°'; const cx=w*.5,cy=h*.52; const headW=w*lerp(.23,.31,chibi), headH=h*lerp(.38,.43,chibi); const eyeY=cy-headH*lerp(.13,.22,chibi)+pitch*35; const noseY=cy+headH*.05+pitch*18, mouthY=cy+headH*.24+pitch*10; ctx.save(); ctx.translate(cx,cy); ctx.scale(1-yaw*yaw*.18,1); const grd=ctx.createRadialGradient(-headW*.18,-headH*.22,10,0,0,headH*.8); grd.addColorStop(0,'#ffe0bd'); grd.addColorStop(.6,'#ffc3a0'); grd.addColorStop(1,shade>0.5?'#b86d78':'#df9c8a'); ctx.fillStyle=grd; ctx.beginPath(); ctx.ellipse(0,0,headW*.5,headH*.5,0,0,TAU); ctx.fill(); ctx.strokeStyle='#24313f'; ctx.lineWidth=3*(devicePixelRatio||1); ctx.stroke(); ctx.restore(); if($('#faceGuides').checked){ ctx.strokeStyle='rgba(74,185,207,.7)'; ctx.lineWidth=2*(devicePixelRatio||1); ctx.setLineDash([9,7]); ctx.beginPath(); ctx.moveTo(cx+yaw*headW*.18,cy-headH*.48); ctx.quadraticCurveTo(cx+yaw*headW*.35,cy,cx+yaw*headW*.08,cy+headH*.48); ctx.stroke(); [eyeY,noseY,mouthY].forEach((y,i)=>{ctx.beginPath();ctx.moveTo(cx-headW*.38,y);ctx.lineTo(cx+headW*.38,y+yaw*12);ctx.stroke();}); ctx.setLineDash([]); }
    const eyeSize=lerp(headW*.055,headW*.105,anime+chibi*.7); [-1,1].forEach(side=>{ const ex=cx+side*headW*lerp(.16,.19,anime)*(1+side*yaw*.32), ey=eyeY+side*yaw*5; ctx.fillStyle='#202b37'; ctx.beginPath(); ctx.ellipse(ex,ey,eyeSize*1.55,eyeSize,side*yaw*.2,0,TAU); ctx.fill(); ctx.fillStyle='#fff'; ctx.beginPath(); ctx.arc(ex-eyeSize*.32,ey-eyeSize*.22,eyeSize*.28,0,TAU); ctx.fill(); }); ctx.strokeStyle='#8f5660'; ctx.lineWidth=3*(devicePixelRatio||1); ctx.beginPath(); ctx.moveTo(cx-yaw*headW*.05,noseY-headH*.12); ctx.quadraticCurveTo(cx+headW*.04,noseY, cx-yaw*headW*.08,noseY+headH*.07); ctx.stroke(); ctx.beginPath(); ctx.arc(cx+yaw*headW*.04,mouthY,headW*.1,0,Math.PI); ctx.stroke(); ctx.fillStyle='rgba(40,50,60,.88)'; ctx.font=`${18*(devicePixelRatio||1)}px Nunito`; ctx.fillText('锚点：中线 / 眼线 / 鼻底 / 嘴线 / 耳点 / 光影边界',24,34*(devicePixelRatio||1)); }

  // fix syntax error: the generated face function will be patched below if necessary

  // Nature lab
  function initNature(){ ['forceAngle','forcePower','noisePower','lineCompression'].forEach(id=>$('#'+id).addEventListener('input',()=>{})); $('#natureModes').addEventListener('click',e=>{ if(e.target.dataset.mode){ state.natureMode=e.target.dataset.mode; $$('#natureModes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.natureMode)); }}); $('#shotNatureBtn').addEventListener('click',()=>downloadDataUrl('drawescape_nature.png',$('#natureCanvas').toDataURL('image/png'))); animateNature(); }
  function animateNature(){ const c=$('#natureCanvas'),ctx=c.getContext('2d'); resizeCanvasToDisplay(c); const w=c.width,h=c.height; const t=performance.now()*0.001; ctx.clearRect(0,0,w,h); ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,w,h); const angle=+$('#forceAngle').value*Math.PI/180, pow=+$('#forcePower').value, noise=+$('#noisePower').value, keep=+$('#lineCompression').value; ctx.fillStyle='#22313c'; ctx.font=`${18*(devicePixelRatio||1)}px Nunito`; ctx.fillText('自然不是轮廓，是力场、密度、边缘、节奏的证据',24,34*(devicePixelRatio||1)); ctx.strokeStyle='#ffd166'; ctx.lineWidth=5*(devicePixelRatio||1); ctx.beginPath(); ctx.moveTo(w*.1,h*.12); ctx.lineTo(w*.1+Math.cos(angle)*80,h*.12+Math.sin(angle)*80); ctx.stroke(); const n=Math.floor(70*keep+18);
    if(state.natureMode==='water'){ ctx.fillStyle='rgba(120,183,230,.22)'; ctx.fillRect(0,h*.42,w,h*.58); ctx.fillStyle='#8e7d6f'; ctx.beginPath(); ctx.ellipse(w*.5,h*.56,w*.08,h*.13,0,0,TAU); ctx.fill(); for(let i=0;i<n;i++){ const y=h*.48+i/n*h*.38; ctx.strokeStyle=`rgba(40,120,160,${.15+.45*i/n})`; ctx.lineWidth=lerp(1,3,i/n)*(devicePixelRatio||1); ctx.beginPath(); for(let x=0;x<w;x+=18){ const dx=x-w*.5, dy=y-h*.56; const avoid=Math.exp(-(dx*dx/(w*w*.025)+dy*dy/(h*h*.018))); const yy=y+Math.sin(x*.02+t*2+i)*10*pow + avoid*55*Math.sin(dx*.02); x?ctx.lineTo(x,yy):ctx.moveTo(x,yy); } ctx.stroke(); } }
    else if(state.natureMode==='smoke'||state.natureMode==='cloud'){ for(let i=0;i<n;i++){ const baseX=w*.2+i/n*w*.6; const baseY=state.natureMode==='smoke'?h*.72:h*.48; const r=lerp(12,80,Math.random()*.7+noise*.3)*(devicePixelRatio||1); const x=baseX+Math.sin(t+i)*70*pow*Math.cos(angle); const y=baseY-Math.sin(i*3+t)*60*pow-(state.natureMode==='smoke'?i/n*h*.35:0); const g=ctx.createRadialGradient(x,y,0,x,y,r); g.addColorStop(0,state.natureMode==='smoke'?'rgba(140,150,165,.18)':'rgba(160,190,220,.22)'); g.addColorStop(1,'rgba(255,255,255,0)'); ctx.fillStyle=g; ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill(); } }
    else { for(let i=0;i<n;i++){ const x=i/n*w; const amp=state.natureMode==='tree'?60:90; const y0=state.natureMode==='tree'?h*.72:h*.52; const len=state.natureMode==='tree'?h*.34:h*.22; ctx.strokeStyle=state.natureMode==='tree'?`rgba(70,125,80,${.25+.5*i/n})`:`rgba(60,90,110,${.18+.5*i/n})`; ctx.lineWidth=lerp(1,4,pow)*(devicePixelRatio||1); ctx.beginPath(); for(let k=0;k<22;k++){ const u=k/21; const sway=Math.sin(t*2+i*.7+u*4)*noise*amp + Math.cos(angle)*pow*amp*u; const yy=y0-len*u + Math.sin(angle)*pow*40*u; const xx=x+sway; k?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy); } ctx.stroke(); if(state.natureMode==='tree'){ ctx.fillStyle='rgba(142,191,148,.22)'; ctx.beginPath(); ctx.arc(x+Math.cos(angle)*pow*30,y0-len*.95,12+20*noise,0,TAU); ctx.fill(); } } }
    requestAnimationFrame(animateNature); }

  // Palette lab
  function initPalette(){ ['baseColor','warmth','satCompress','comicContrast'].forEach(id=>$('#'+id).addEventListener('input',drawPalette)); $('#savePaletteBtn').addEventListener('click',()=>{ state.palette=currentPalette(); saveState(); toast('配色已保存'); }); drawPalette(); }
  function currentPalette(){ const base=$('#baseColor').value, warm=+$('#warmth').value, comp=+$('#comicContrast').value, sat=+$('#satCompress').value; const hi=mix(shade(base,.32), warm>0?'#ffd166':'#bfe9ff',Math.abs(warm)*.45); const shadow=mix(shade(base,-.42), warm>0?'#32476f':'#68435f',.35+sat*.25); const ambient=mix(base,warm>0?'#78b7e6':'#ffad6e',.42); const accent=mix(mix(base,'#ffffff',.1),'#ff4fa3',comp*.35); return [{name:'固有色',color:base},{name:'亮部/光照',color:hi},{name:'暗部/体积',color:shadow},{name:'环境反光',color:ambient},{name:'漫画强调',color:accent},{name:'纸面留白',color:'#fffaf0'}]; }
  function drawPalette(){ const pal=currentPalette(); const sw=$('#swatches'); sw.innerHTML=''; pal.forEach(p=>{ const d=document.createElement('div'); d.className='swatch'; d.style.background=p.color; d.textContent=p.name+' '+p.color; sw.appendChild(d); }); const c=$('#paletteCanvas'),ctx=c.getContext('2d'); resizeCanvasToDisplay(c); const w=c.width,h=c.height; ctx.clearRect(0,0,w,h); ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,w,h); const cx=w*.42,cy=h*.46,r=Math.min(w,h)*.22; const g=ctx.createRadialGradient(cx-r*.35,cy-r*.38,10,cx,cy,r); g.addColorStop(0,pal[1].color); g.addColorStop(.48,pal[0].color); g.addColorStop(1,pal[2].color); ctx.fillStyle=g; ctx.beginPath();ctx.arc(cx,cy,r,0,TAU);ctx.fill(); ctx.fillStyle=pal[3].color; ctx.globalAlpha=.32;ctx.beginPath();ctx.arc(cx+r*.38,cy+r*.28,r*.45,0,TAU);ctx.fill();ctx.globalAlpha=1; ctx.fillStyle=pal[4].color;ctx.beginPath();ctx.arc(cx-r*.26,cy-r*.28,r*.14,0,TAU);ctx.fill(); ctx.fillStyle='#22313c';ctx.font=`${18*(devicePixelRatio||1)}px Nunito`;ctx.fillText('颜色通道：固有色 × 光照 × 环境 × 情绪强调',24,36*(devicePixelRatio||1)); pal.forEach((p,i)=>{ ctx.fillStyle=p.color; ctx.fillRect(w*.72,90+i*56,120,36); ctx.strokeStyle='rgba(35,49,60,.2)';ctx.strokeRect(w*.72,90+i*56,120,36); ctx.fillStyle='#22313c';ctx.fillText(p.name,w*.72+140,115+i*56); }); }

  // Emotion lab
  const emotions={quiet:{name:'安静',color:'#78b7e6',line:.35,contrast:.25,space:.8,text:'安静可以用低对比、长线、留白、水平构图表达。'},tension:{name:'紧张',color:'#e46a6a',line:.9,contrast:.9,space:.25,text:'紧张可以用尖角、倾斜、强对比、压缩空间表达。'},warm:{name:'温暖',color:'#ffd166',line:.55,contrast:.45,space:.65,text:'温暖可以用暖光、圆形、近距离关系、柔边缘表达。'},lonely:{name:'孤独',color:'#8c75df',line:.4,contrast:.55,space:.95,text:'孤独可以用大面积留白、远距离、低饱和冷色表达。'},courage:{name:'勇气',color:'#ffad6e',line:.8,contrast:.7,space:.45,text:'勇气可以用上升线、稳定三角构图、明亮高光表达。'},dream:{name:'梦',color:'#f39ab2',line:.5,contrast:.35,space:.7,text:'梦可以用软边、漂浮结构、非现实比例和渐变表达。'}};
  function initEmotion(){ const box=$('#emotionChips'); Object.entries(emotions).forEach(([k,e])=>{ const b=document.createElement('button'); b.textContent=e.name; b.dataset.emotion=k; if(k==='quiet') b.classList.add('active'); box.appendChild(b); }); box.addEventListener('click',e=>{ if(e.target.dataset.emotion){ state.emotion=e.target.dataset.emotion; $$('#emotionChips button').forEach(b=>b.classList.toggle('active',b.dataset.emotion===state.emotion)); drawEmotion(); }}); ['emotionIntensity','structureControl','abstractLevel'].forEach(id=>$('#'+id).addEventListener('input',drawEmotion)); $('#shotEmotionBtn').addEventListener('click',()=>downloadDataUrl('drawescape_emotion_card.png',$('#emotionCanvas').toDataURL('image/png'))); drawEmotion(); }
  function drawEmotion(){ const e=emotions[state.emotion], c=$('#emotionCanvas'),ctx=c.getContext('2d'); resizeCanvasToDisplay(c); const w=c.width,h=c.height; const inten=+$('#emotionIntensity').value, control=+$('#structureControl').value, abs=+$('#abstractLevel').value; ctx.clearRect(0,0,w,h); ctx.fillStyle=mix('#fffdf6',e.color,.12+inten*.1);ctx.fillRect(0,0,w,h); ctx.fillStyle='#22313c';ctx.font=`${20*(devicePixelRatio||1)}px Nunito`; ctx.fillText(`感受：${e.name} → 视觉语言`,24,40*(devicePixelRatio||1)); ctx.strokeStyle=mix(e.color,'#1f2c35',.35); ctx.lineWidth=lerp(1,10,e.line*inten)*(devicePixelRatio||1); ctx.lineCap='round'; const cx=w*.46,cy=h*.55; for(let i=0;i<12;i++){ const a=i/12*TAU + (e.name==='紧张'?.2:0); const r=lerp(80,210, e.space)*(devicePixelRatio||1)*(1+Math.sin(i)*.08); ctx.beginPath(); if(state.emotion==='tension'){ ctx.moveTo(cx,cy); ctx.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r*.72); } else { ctx.moveTo(cx+Math.cos(a)*r*.2,cy+Math.sin(a)*r*.14); ctx.bezierCurveTo(cx+Math.cos(a+.8)*r*.55,cy+Math.sin(a+.8)*r*.34,cx+Math.cos(a-.5)*r*.8,cy+Math.sin(a-.5)*r*.55,cx+Math.cos(a)*r,cy+Math.sin(a)*r*.72); } ctx.stroke(); }
    ctx.globalAlpha=.25+inten*.35; ctx.fillStyle=e.color; for(let i=0;i<9;i++){ ctx.beginPath(); const rr=lerp(18,80,Math.random()); ctx.arc(cx+Math.cos(i*2.1)*180*e.space,cy+Math.sin(i*1.7)*120,rr*(1+abs),0,TAU); ctx.fill(); } ctx.globalAlpha=1; ctx.strokeStyle='rgba(35,49,60,.22)';ctx.lineWidth=2*(devicePixelRatio||1); if(control>.4){ ctx.strokeRect(w*.18,h*.24,w*.56,h*.54); ctx.beginPath();ctx.moveTo(w*.18,h*.51);ctx.lineTo(w*.74,h*.51);ctx.stroke(); }
    $('#emotionText').innerHTML=`<b>${e.name}如何翻译成画？</b><p>${e.text}</p><p>结构控制越高，画面越稳定；抽象程度越高，越少依赖具体对象，而靠线条/颜色/空间表达。</p>`; }

  function initScreenshots(){ ['shotPerspectiveBtn','shotNatureBtn'].forEach(()=>{}); }

  // Initialization
  function init(){ loadState(); initUI(); initCover(); initWebGLLab(); initPerspective(); initShading(); initFace(); initNature(); initPalette(); initEmotion(); initScreenshots(); }
  document.addEventListener('DOMContentLoaded',init);
})();
